[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xopr-gline"
version = "0.1.0"
description = "Automated grounding point detection using xOPR"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "earthaccess>=0.16.0",
    "requests>=2.32.0",
    "rioxarray>=0.19.0",
    "tqdm>=4.67.0",
    "xopr>=0.3.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/xopr_gline"]

[tool.uv.sources]
xopr = { git = "https://github.com/englacial/xopr.git" }

[dependency-groups]
dev = [
    "bayesian-changepoint-detection==0.2.dev1",
    "decorator>=5.3.1",
    "hvplot>=0.12.2",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "jupyterlab>=4.6.2",
    "pytest>=9.0.2",
]
